class PrecRtdSimRegs:
    SYS_UPTIME = "SYS_UPTIME"
    SYS_REGMAP_VERSION = "SYS_REGMAP_VERSION"
    SYS_STATUS = "SYS_STATUS"
    SYS_COMMAND = "SYS_COMMAND"
    SYS_TEST = "SYS_TEST"
    SYS_IO_INPUT = "SYS_IO_INPUT"
    FACT_SERIAL_NUMBER = "FACT_SERIAL_NUMBER"
    FACT_DEVICE_ID = "FACT_DEVICE_ID"
    FACT_HW_REVISION = "FACT_HW_REVISION"
    FACT_BOOT_REVISION = "FACT_BOOT_REVISION"
    FIRM_REVISION = "FIRM_REVISION"
    FIRM_ASSEMBLY_INFO = "FIRM_ASSEMBLY_INFO"
    COM_MB_BAUD_RATE = "COM_MB_BAUD_RATE"
    COM_MB_PARITY = "COM_MB_PARITY"
    COM_MB_STOP_BITS = "COM_MB_STOP_BITS"
    COM_RESERVED = "COM_RESERVED"
    COM_MB_ADDRESS = "COM_MB_ADDRESS"
    COM_MB_APPLY = "COM_MB_APPLY"
    COM_MB_TIMEOUT = "COM_MB_TIMEOUT"
    RTD_MODE = "RTD_MODE"
    RTD_CHANNEL_SELECT = "RTD_CHANNEL_SELECT"
    RTD_EXP_BOARD1_ADDR1 = "RTD_EXP_BOARD1_ADDR1"
    RTD_EXP_BOARD1_ADDR2 = "RTD_EXP_BOARD1_ADDR2"
    RTD_EXP_BOARD2_ADDR1 = "RTD_EXP_BOARD2_ADDR1"
    RTD_EXP_BOARD2_ADDR2 = "RTD_EXP_BOARD2_ADDR2"
    RTD_EXP_BOARD_INIT = "RTD_EXP_BOARD_INIT"
    RTD_NTC_BETA = "RTD_NTC_BETA"
    RTD_NTC_STOCK_RES = "RTD_NTC_STOCK_RES"
    RTD_PT_STOCK_RES = "RTD_PT_STOCK_RES"
    RTD_RESISTANCE = "RTD_RESISTANCE"
    RTD_TEMPERATURE = "RTD_TEMPERATURE"
    RTD_SLEWRATE_MODE = "RTD_SLEWRATE_MODE"
    RTD_SLEWRATE = "RTD_SLEWRATE"
    RTD_SLEWRATE_MAX = "RTD_SLEWRATE_MAX"
    RTD_SLEWRATE_MIN = "RTD_SLEWRATE_MIN"
    DBG_WRITES_CONF = "DBG_WRITES_CONF"


class COM_MB_BAUD_RATE:
    MB_BAUD_9600 = 0
    MB_BAUD_19200 = 1
    MB_BAUD_38400 = 2
    MB_BAUD_57600 = 3
    MB_BAUD_115200 = 4


class COM_MB_PARITY:
    MB_PARITY_NONE = 0
    MB_PARITY_EVEN = 1
    MB_PARITY_ODD = 2


class COM_MB_STOP_BITS:
    MB_STOP_1 = 0
    MB_STOP_2 = 1


class RTD_MODE:
    RTD_MD_RESISTANCE = 0
    RTD_MD_NTC = 1
    RTD_MD_PLATINUM = 2


class RTD_EXP_BOARD1_ADDR1:
    B1_ADDR1_000 = 0
    B1_ADDR1_001 = 1
    B1_ADDR1_010 = 2
    B1_ADDR1_011 = 3
    B1_ADDR1_100 = 4
    B1_ADDR1_101 = 5
    B1_ADDR1_110 = 6
    B1_ADDR1_111 = 7


class RTD_EXP_BOARD1_ADDR2:
    B1_ADDR2_000 = 0
    B1_ADDR2_001 = 1
    B1_ADDR2_010 = 2
    B1_ADDR2_011 = 3
    B1_ADDR2_100 = 4
    B1_ADDR2_101 = 5
    B1_ADDR2_110 = 6
    B1_ADDR2_111 = 7


class RTD_EXP_BOARD2_ADDR1:
    B2_ADDR1_000 = 0
    B2_ADDR1_001 = 1
    B2_ADDR1_010 = 2
    B2_ADDR1_011 = 3
    B2_ADDR1_100 = 4
    B2_ADDR1_101 = 5
    B2_ADDR1_110 = 6
    B2_ADDR1_111 = 7


class RTD_EXP_BOARD2_ADDR2:
    B2_ADDR2_000 = 0
    B2_ADDR2_001 = 1
    B2_ADDR2_010 = 2
    B2_ADDR2_011 = 3
    B2_ADDR2_100 = 4
    B2_ADDR2_101 = 5
    B2_ADDR2_110 = 6
    B2_ADDR2_111 = 7


class RTD_SLEWRATE_MODE:
    RTD_SLEWRATE_OFF = 0
    RTD_SLEWRATE_ON = 1


