class PrecRtdSimRegs:
    SYS_UPTIME = "SYS_UPTIME"
    SYS_REGMAP_VERSION = "SYS_REGMAP_VERSION"
    SYS_STATUS = "SYS_STATUS"
    SYS_ERROR = "SYS_ERROR"
    SYS_COMMAND = "SYS_COMMAND"
    SYS_TEST = "SYS_TEST"
    SYS_FREQUENCY = "SYS_FREQUENCY"
    SYS_DUTY = "SYS_DUTY"
    SYS_BUZZER_TIME = "SYS_BUZZER_TIME"
    SYS_BUZZER_MODE = "SYS_BUZZER_MODE"
    SYS_BUZZER_BOOST = "SYS_BUZZER_BOOST"
    FACT_SERIAL_NUMBER = "FACT_SERIAL_NUMBER"
    FACT_DEVICE_ID = "FACT_DEVICE_ID"
    FACT_HW_REVISION = "FACT_HW_REVISION"
    FACT_BOOT_REVISION = "FACT_BOOT_REVISION"
    FIRM_REVISION = "FIRM_REVISION"
    FIRM_ASSEMBLY_INFO = "FIRM_ASSEMBLY_INFO"
    FIRM_APP_CHECKSUM = "FIRM_APP_CHECKSUM"
    FIRM_APP_SIZE = "FIRM_APP_SIZE"
    ANL_PERIOD = "ANL_PERIOD"
    ANL_FILTER = "ANL_FILTER"
    ANL_AD1 = "ANL_AD1"
    ANL_AD2 = "ANL_AD2"
    ANL_AD3 = "ANL_AD3"
    ANL_AD4 = "ANL_AD4"
    ANL_AD5 = "ANL_AD5"
    ANL_AD6 = "ANL_AD6"
    PWR_ACCU_DCHRG = "PWR_ACCU_DCHRG"
    PWR_ACCU_LOAD = "PWR_ACCU_LOAD"
    PWR_ACCU_TEST = "PWR_ACCU_TEST"
    PWR_USD_VDD_EN = "PWR_USD_VDD_EN"
    PWR_ACCU_CSCO = "PWR_ACCU_CSCO"
    PWR_AC_PRESENT = "PWR_AC_PRESENT"
    PWR_MUX_STAT = "PWR_MUX_STAT"
    PWR_ACCU_CHRG = "PWR_ACCU_CHRG"
    PWR_VREF = "PWR_VREF"
    PWR_ACCU_MEAS = "PWR_ACCU_MEAS"
    PWR_VOUT_MEAS = "PWR_VOUT_MEAS"
    PWR_CURR1_MEAS = "PWR_CURR1_MEAS"
    PWR_CURR2_MEAS = "PWR_CURR2_MEAS"
    PWR_ACCU_NTC = "PWR_ACCU_NTC"
    PWR_ACCU_HEAT = "PWR_ACCU_HEAT"
    PWR_ACCU_HEAT_MANUAL = "PWR_ACCU_HEAT_MANUAL"
    GSM_PWR_EN = "GSM_PWR_EN"
    GSM_PWR_KEY = "GSM_PWR_KEY"
    GSM_RESET = "GSM_RESET"
    GSM_PRESENT = "GSM_PRESENT"


class SYS_BUZZER_MODE:
    SYS_BUZZER_TONE = 0
    SYS_BUZZER_SWEEP = 1


class PWR_ACCU_CSCO:
    CSCO_IDLE = 0
    CSCO_CHARGING = 1
    CSCO_ERROR = 2


class PWR_ACCU_HEAT:
    PWR_ACCU_NO_HEAT = 0
    PWR_ACCU_SINGLE_HEAT = 1
    PWR_ACCU_FULL_HEAT = 2


